FROM alpine
RUN apk --no-cache add curl git npm
ARG GIT_REPO
RUN git clone https://github.com/Piterson25/React_test /app
WORKDIR /app/react_app
RUN npm install
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]
