version: '3'
services:
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
  db:
    image: mongo
    ports:
      - 27019:27017
    volumes:
      - mongo_data:/data/db
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - redis
      - db
volumes:
  redis_data:
  mongo_data: