version: "3.8"
services:
  web:
    build: .
    ports:
      - 80:3000
    depends_on:
      - redis
      - postgres
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp
