apiVersion: apps/v1
kind: Deployment
metadata:
  name: baza-danych-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baza-danych
  template:
    metadata:
      labels:
        app: baza-danych
    spec:
      containers:
      - name: baza-danych
        image: piterson25/baza_danych:latest
        ports:
        - containerPort: 27017
