apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikroserwis-a-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mikroserwis-a
  template:
    metadata:
      labels:
        app: mikroserwis-a
    spec:
      containers:
      - name: mikroserwis-a
        image: piterson25/mikroserwis_a:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
          requests:
            memory: "500Mi"
            cpu: "500m"
